from agentskill.lib.agents_document import (
    AgentsSection,
    add_or_replace_section,
    get_section,
    normalize_section_name,
    parse_agents_document,
    replace_section,
    serialize_agents_document,
)


def test_parse_empty_document():
    document = parse_agents_document("")

    assert document.preamble == ""
    assert document.sections == []
    assert serialize_agents_document(document) == ""


def test_parse_preamble_and_multiple_sections():
    text = (
        "Intro line.\n"
        "Still preamble.\n\n"
        "# Overview\n"
        "Top-level body.\n"
        "## Details\n"
        "More detail.\n"
    )

    document = parse_agents_document(text)

    assert document.preamble == "Intro line.\nStill preamble.\n\n"
    assert document.sections == [
        AgentsSection(
            heading_text="Overview",
            normalized_name="",
            heading_level=1,
            body="Top-level body.\n",
        ),
        AgentsSection(
            heading_text="Details",
            normalized_name="",
            heading_level=2,
            body="More detail.\n",
        ),
    ]


def test_unknown_custom_sections_round_trip_unchanged():
    text = (
        "Custom intro.\n\n"
        "## House Style\n"
        "Keep this text.\n"
        "### Team Notes\n"
        "- Preserve bullets\n"
    )

    assert serialize_agents_document(parse_agents_document(text)) == (
        "Custom intro.\n\n"
        "## House Style\n\n"
        "Keep this text.\n\n"
        "### Team Notes\n\n"
        "- Preserve bullets\n\n"
    )


def test_lookup_uses_normalized_section_names():
    text = "# Coding   Conventions\nUse double quotes.\n"
    document = parse_agents_document(text)

    assert normalize_section_name(" Coding conventions ") == "coding conventions"
    assert get_section(document, "coding conventions") == AgentsSection(
        heading_text="Coding   Conventions",
        normalized_name="",
        heading_level=1,
        body="Use double quotes.\n",
    )


def test_replace_section_updates_only_first_matching_section():
    text = "Before.\n\n# Overview\nOriginal overview.\n## Conventions\nKeep this.\n"
    document = parse_agents_document(text)

    replacement = AgentsSection(
        heading_text="Overview",
        normalized_name="",
        heading_level=1,
        body="Updated overview.\n",
    )

    updated = replace_section(document, replacement)

    assert serialize_agents_document(updated) == (
        "Before.\n\n# Overview\n\nUpdated overview.\n\n## Conventions\n\nKeep this.\n\n"
    )


def test_add_or_replace_section_appends_when_missing():
    text = "# Overview\nBase content.\n"
    document = parse_agents_document(text)

    section = AgentsSection(
        heading_text="Custom Notes",
        normalized_name="",
        heading_level=2,
        body="Appended content.\n",
    )

    updated = add_or_replace_section(document, section)
    assert serialize_agents_document(updated) == (
        "# Overview\n\nBase content.\n\n## Custom Notes\n\nAppended content.\n\n"
    )


def test_round_trip_preserves_representative_document():
    text = (
        "Generated by agentskill.\n"
        "Manual notes stay here.\n\n"
        "# Overview\n"
        "Summary paragraph.\n\n"
        "## Commands\n"
        "```bash\n"
        "agentskill analyze repo --pretty\n"
        "```\n\n"
        "### Local Notes\n"
        "Do not remove this section.\n"
    )

    assert serialize_agents_document(parse_agents_document(text)) == (
        "Generated by agentskill.\n"
        "Manual notes stay here.\n\n"
        "# Overview\n\n"
        "Summary paragraph.\n\n"
        "## Commands\n\n"
        "```bash\n"
        "agentskill analyze repo --pretty\n"
        "```\n\n"
        "### Local Notes\n\n"
        "Do not remove this section.\n\n"
    )
